version: '3'

services:

  flask-app:
    build: flask-app/
    ports:
      - "5000:5000"
      - "5001:5001"
      - "3000:3000"
    volumes:
      - ./flask-app:/usr/src/app/
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: flask run --host 0.0.0.0
